name: lesion_similarity_analysis
channels:
- conda-forge
- defaults
dependencies:
- "python >= 3.6"
- numpy
- scipy
- scikit-image
- dask
- xarray
- napari
- matplotlib
- pandas
- jupyter
- jupyterlab
- nb_conda
- setuptools
- "pytest >= 2.7.1"
- pytest-cov
- setuptools
- pip
- pip:
  - nb_black
